version: '3'

services:
  # Redis service
  redis:
    image: redis:alpine3.17
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_cache:/data
    container_name: visa_scraper_redis

  # Django service
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - redis
    container_name: visa_scraper_web

  # Celery worker
  celery:
    build: .
    restart: always
    command: celery -A config worker --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    container_name: visa_scraper_celery

# Volumes
volumes:
  redis_cache:
